version: "3.9"

services:
  db:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: moviesdb
      MARIADB_USER: movies
      MARIADB_PASSWORD: moviespwd
      MARIADB_ROOT_PASSWORD: rootpwd
      OLLAMA_URL: http://ollama:11434
    ports:
      - "3307:3306" # host:container (config default expects 3307 on host)
    volumes:
      - ./mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "127.0.0.1", "-u", "root", "-prootpwd"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: movies
      DB_PASSWORD: moviespwd
      DB_NAME: moviesdb
      APP_PORT: 8003
      #prova per seed
      SEED_TSV: /seed/data.tsv
    volumes:
      - ./data.tsv:/seed/data.tsv:ro
      #fine prova
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8003:8003"

  frontend:
    build: ./frontend
    restart: unless-stopped
    environment:
      BACKEND_URL: http://backend:8003
      APP_PORT: 8000

      USE_OLLAMA_CHAT: "true"
      OLLAMA_URL: http://ollama:11434

    depends_on:
      backend:
        condition: service_started
      ollama:        
        condition: service_started
    ports:
      - "8000:8000"

  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama

volumes:
  mariadb_data:
  ollama:




